name: Test
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.7'
          cache: 'pnpm'
      - run: pnpm install
      - name: Run Test
        run: pnpm test
